eventus/apps/events/urls.py
from django.conf.urls import url
from .views import IndexView, MainPanelView, CreateEvent, EventDetail, MainRegistroPanelView, CrearRegistro
urlpatterns = [
    url(r'^$', IndexView.as_view(), name="index"),

    url(r'^panel/$', MainPanelView.as_view(), name='panel'),
    url(r'^panel/evento/nuevo/$', CreateEvent.as_view(), name='nuevo'),
    url(r'^panel/evento/(?P<pk>\d+)/$', EventDetail.as_view(), name='detalle'),

    url(r'^registro/$', MainRegistroPanelView.as_view(), name='registropanel'),
    url(r'^registro/asistente/nuevo$', CrearRegistro.as_view(), name='nueva_asistencia'),


]

eventus/eventus/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('apps.events.urls', namespace="events_app")),
    url(r'^admin/', include(admin.site.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventus/apps/events/models.py
from django.db import models

# Create your models here.

eventus/apps/events/models/asistente.py
from django.db import models
from .categoria import TimeStampModel
from .evento import Evento
from django.conf import settings


class Asistente(TimeStampModel):
    # falta crear modelo usuario
    asistente = models.ForeignKey(settings.AUTH_USER_MODEL)
    evento = models.ManyToManyField(Evento)
    asistio = models.BooleanField(default=False)
    ha_pagado = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Asistente"
        verbose_name_plural = "Asistentes"

    def __str__(self):
        return "%s %s" % (self.asistente.nombreusuario, self.evento.nombre)

eventus/apps/events/models/categoria.py
from django.db import models
from django.template.defaultfilters import slugify


class TimeStampModel(models.Model):

    creacion = models.DateTimeField(auto_now_add=True)
    modificacion = models.DateField(auto_now=True)

    class Meta:
        abstract = True
        verbose_name = "TimeStampModel"
        verbose_name_plural = "TimeStampModels"


class Categoria(models.Model):

    nombre = models.CharField(max_length=50)
    slug = models.SlugField(editable=False)

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"

    def save(self, *args, **kwargs):
        if not self.id:
                    self.slug = slugify(self.nombre)
        super(Categoria, self).save(*args, **kwargs)

    def __str__(self):
        return self.nombre

eventus/apps/events/models/comentario.py
from django.db import models
from .categoria import TimeStampModel
from .evento import Evento
from django.conf import settings


class Comentarios(TimeStampModel):

    usuario = models.ForeignKey(settings.AUTH_USER_MODEL)
    evento = models.ForeignKey(Evento)

    contenido = models.TextField()

    class Meta:
        verbose_name = "Comentarios"
        verbose_name_plural = "Comentarioss"

    def __str__(self):
        return "%s %s" % (self.usuario.nombreusuario, self.evento.nombre)

eventus/apps/events/models/evento.py
from django.db import models
from .categoria import TimeStampModel, Categoria
from django.conf import settings
from django.template.defaultfilters import slugify


def upload_location(instance, filename):
    return "%s %s " % (instance.id, filename)


class Evento(TimeStampModel):
    nombre = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(editable=False)
    resumen = models.TextField(max_length=255)
    contenido = models.TextField()
    categoria = models.ForeignKey(Categoria)
    lugar = models.CharField(max_length=50)
    fecha_inicio = models.DateTimeField()
    fecha_fin = models.DateTimeField()
    imagen = models.ImageField(upload_to=upload_location,
                               null=True, blank=True,
                               height_field="height_field",
                               width_field="width_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    es_libre = models.BooleanField(default=True)
    costo = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    numero_visitas = models.PositiveIntegerField(default=0)
    organizador = models.ForeignKey(
        settings.AUTH_USER_MODEL)  # Falta crear  Usuarios

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.nombre)
        super(Evento, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Evento"
        verbose_name_plural = "Eventos"

    def __str__(self):
        return self.nombre

eventus/apps/events/models/registro.py
from django.db import models
from .categoria import TimeStampModel
from ..choices.enums import GENERO_CHOICES, PROVINCIAS_CHOICES, ENTERECE_CHOICES


class Registro(TimeStampModel):
    nombre = models.CharField(max_length=80)
    apellidos = models.CharField(max_length=150)
    email = models.EmailField()
    celular = models.CharField(max_length=9)
    organizacion = models.CharField(max_length=150)
    provincia = models.CharField(max_length=100, choices=PROVINCIAS_CHOICES)
    distrito = models.CharField(max_length=100)
    genero = models.CharField(
        max_length=40, choices=GENERO_CHOICES, blank=True)
    edad = models.IntegerField()
    me_entere = models.CharField(
        max_length=60, choices=ENTERECE_CHOICES, blank=True)

    class Meta:
        verbose_name = "Registro"
        verbose_name_plural = "Registros"

    def __str__(self):
        return self.nombre

eventus/apps/events/forms.py
from django import forms
from .models.evento import Evento
from .models.registro import Registro


class EventoForm(forms.ModelForm):

    class Meta:
        model = Evento
        exclude = ('views', 'created', 'modified',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'summary': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'place': forms.TextInput(attrs={'class': 'form-control'}),
            'start': forms.DateTimeInput(attrs={'class': 'form-control'}),
            'finish': forms.DateTimeInput(attrs={'class': 'form-control'}),
            'imagen': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'is_free': forms.CheckboxInput(),
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
        }


class RegistroForm(forms.ModelForm):

    class Meta:
        model = Registro
        fields = (
            'nombre',
            'apellidos',
            'email',
            'celular',
            'organizacion',
            'provincia',
            'distrito',
            'genero',
            'edad',
            'me_entere',
        )

eventus/apps/events/views.py
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView
from .models.evento import Evento
from .models.categoria import Categoria
from .models.registro import Registro
from .forms import EventoForm, RegistroForm

# Create your views here.


from django.core.urlresolvers import reverse_lazy


# seccion de creacion views de  registro

class MainRegistroPanelView(TemplateView):

    template_name = 'events/registro/registro.html'

    def get_context_data(self, **kwargs):
        context = super(MainRegistroPanelView, self).get_context_data(**kwargs)
        context['asistentes'] = Registro.objects.all()
        return context


class CrearRegistro(CreateView):

    form_class = RegistroForm
    template_name = 'events/registro/crear_registro.html'
    success_url = reverse_lazy('events_app:registropanel')

    def form_valid(self, form):

        return super(CrearRegistro, self).form_valid(form)


# Seccion de creacion de views de Evento

class IndexView(TemplateView):

    template_name = 'events/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['events'] = Evento.objects.all()
        context['categorias'] = Categoria.objects.all()
        return context


class MainPanelView(TemplateView):

    template_name = 'events/panel/panel.html'

    def get_context_data(self, **kwargs):
        context = super(MainPanelView, self).get_context_data(**kwargs)
        context['events'] = Evento.objects.all()
        context['cantidad'] = context['events'].count()
        return context


class EventDetail(DetailView):

    template_name = 'events/panel/detalle_evento.html'
    model = Evento


class CreateEvent(CreateView):

    form_class = EventoForm
    template_name = 'events/panel/crear_evento.html'
    success_url = reverse_lazy('events_app:panel')

    def form_valid(self, form):
        form.instance.organizer = self.request.user
        return super(CreateEvent, self).form_valid(form)


class EventEdit(UpdateView):

    template_name = 'events/panel/editar_evento.html'
    success_url = reverse_lazy('events_app:panel')
    model = Evento
    form_class = EventoForm

    def form_valid(self, form):
        form.instance.organizer = self.request.user
        return super(EventEdit, self).form_valid(form)


class EventDelete(DeleteView):

    template_name = 'events/panel/eliminar_evento.html'
    model = Evento
    success_url = reverse_lazy('events_app:panel')
    context_object_name = 'event'

eventus/apps/events/templates/events/base_events.html
{% extends "base.html" %} 


{% load staticfiles %}
{% block css %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/estilos.css" %}">
{% endblock css %}


{% block js %}
	<script src="{% static "js/bootstrap.min.js " %}"></script>
{% endblock js %}

eventus/apps/events/templates/events/index.html
{% extends "events/base_events.html" %}

{% block title %} Home {% endblock title %}

{% block content %}

	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
	    <div class="container">
	        <div class="navbar-header">
	            <nav class="navbar navbar-inverse navbar-fixed-top">
	        			<div class="container">
	        				<div class="navbar-header">
	        					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false" aria-controls="navbar">
	        						<span class="sr-only">Toogle navigation</span>
	        						<span class="icon-bar"></span>
	        						<span class="icon-bar"></span>
	        						<span class="icon-bar"></span>
	        					</button>
	        					<img src="">
	        					 <a class="navbar-brand" href="">Eventus</a>
	        				</div>
	        				<div id="navbar" class="collapse navbar-collapse">
	        					<ul class="nav navbar-nav navbar-right" >
	        						<li><a href="#nosotros-wraper">Nosotros</a></li>
	        						<li><a href="#contacto-wraper">Contacto</a></li>
	        						<li><a href="#">Sign Up / Login</a></li> 
	        					</ul>
	        				</div>
	        			</div>
	        	</nav>

	        </div>
	        <!--/.nav-collapse -->
		</div>
	</div>

	<div class="jumbotron">
	  <div class="container text-center">
	    <h1>EVENTUS</h1>
	    <p>Bienvenido a EVENTUS, aquí podrás encontrar los eventos que realiza Caminos del Inkarri "TURISMO RURAL COMUNITARIO".</p>
	  </div>
	</div>

	<div class="container">

	    <div class="page-header">
	        <h4><strong>Eventos disponibles</strong></h4>
	    </div>

	    <div class="row">
	        
	        <div class="col-md-2">
	            <div class="input-group">
	                <span class="input-group-addon"><span class="glyphicon glyphicon-tag"></span></span>
	                <select class="form-control">
	                    <option>Categoría</option>
	                </select>
	            </div>
	        </div>
	        <div class="col-md-2">
	            <div class="input-group">
	                <span class="input-group-addon"><span class="glyphicon glyphicon-credit-card"></span></span>
	            <select class="form-control">
	                <option>Tipo pago</option>
	            </select>
	            </div>
	        </div>
	        <div class="col-md-8">
	            <div class="input-group">
	                <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
	                <input type="text" class="form-control" placeholder="Busca el evento de tu gusto">
	            </div>
	        </div>

	    </div>

	</div>

	<p></p>

	<div class="container eventos">    
	    
	    <div class="row contenedor-eventos">
	        {% for event in events %}
	        
	        <div class="col-sm-1 col-md-8">
	            <div class="thumbnail equal">
	                <div class="caption">
	                    <h4><a href="">{{ event.nombre }}</a></h4>
	                    <small class="date">{{ event.fecha_inicio }}</small>
	                    <div class="place">
	                        <small class="place">{{ event.lugar}}</small> 
	                    </div>
	                    <span class="views">{{ event.visitas }}</span>
	                </div>
	                <img src="{{ event.imagen.url }}" >
	            </div>
	            
	        </div>
	        <div class="col-sm-1 col-md-4">
	        	<h2>¡<a href="{% url 'events_app:nueva_asistencia' %}" role="button">Registrate</a> y participa en el evento!</h2>
	        </div>
	        {% endfor %}
	        
	    </div>

	</div>

		

{% endblock content %}