eventus/apps/events/urls.py
from django.conf.urls import url
from .views import IndexView, MainPanelView, CreateEvent, EventDetail, MainRegistroPanelView, CrearRegistro
urlpatterns = [
    url(r'^$', IndexView.as_view(), name="index"),

    url(r'^panel/$', MainPanelView.as_view(), name='panel'),
    url(r'^panel/evento/nuevo/$', CreateEvent.as_view(), name='nuevo'),
    url(r'^panel/evento/(?P<pk>\d+)/$', EventDetail.as_view(), name='detalle'),

    url(r'^registro/$', MainRegistroPanelView.as_view(), name='registropanel'),
    url(r'^registro/asistente/nuevo$', CrearRegistro.as_view(), name='nueva_asistencia'),


]

eventus/eventus/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('apps.events.urls', namespace="events_app")),
    url(r'^admin/', include(admin.site.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventus/apps/events/models.py
from django.db import models

# Create your models here.

eventus/apps/events/models/asistente.py
from django.db import models
from .categoria import TimeStampModel
from .evento import Evento
from django.conf import settings


class Asistente(TimeStampModel):
    # falta crear modelo usuario
    asistente = models.ForeignKey(settings.AUTH_USER_MODEL)
    evento = models.ManyToManyField(Evento)
    asistio = models.BooleanField(default=False)
    ha_pagado = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Asistente"
        verbose_name_plural = "Asistentes"

    def __str__(self):
        return "%s %s" % (self.asistente.nombreusuario, self.evento.nombre)

eventus/apps/events/models/categoria.py
from django.db import models
from django.template.defaultfilters import slugify


class TimeStampModel(models.Model):

    creacion = models.DateTimeField(auto_now_add=True)
    modificacion = models.DateField(auto_now=True)

    class Meta:
        abstract = True
        verbose_name = "TimeStampModel"
        verbose_name_plural = "TimeStampModels"


class Categoria(models.Model):

    nombre = models.CharField(max_length=50)
    slug = models.SlugField(editable=False)

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"

    def save(self, *args, **kwargs):
        if not self.id:
                    self.slug = slugify(self.nombre)
        super(Categoria, self).save(*args, **kwargs)

    def __str__(self):
        return self.nombre

eventus/apps/events/models/comentario.py
from django.db import models
from .categoria import TimeStampModel
from .evento import Evento
from django.conf import settings


class Comentarios(TimeStampModel):

    usuario = models.ForeignKey(settings.AUTH_USER_MODEL)
    evento = models.ForeignKey(Evento)

    contenido = models.TextField()

    class Meta:
        verbose_name = "Comentarios"
        verbose_name_plural = "Comentarioss"

    def __str__(self):
        return "%s %s" % (self.usuario.nombreusuario, self.evento.nombre)

eventus/apps/events/models/evento.py
from django.db import models
from .categoria import TimeStampModel, Categoria
from django.conf import settings
from django.template.defaultfilters import slugify


def upload_location(instance, filename):
    return "%s %s " % (instance.id, filename)


class Evento(TimeStampModel):
    nombre = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(editable=False)
    resumen = models.TextField(max_length=255)
    contenido = models.TextField()
    categoria = models.ForeignKey(Categoria)
    lugar = models.CharField(max_length=50)
    fecha_inicio = models.DateTimeField()
    fecha_fin = models.DateTimeField()
    imagen = models.ImageField(upload_to=upload_location,
                               null=True, blank=True,
                               height_field="height_field",
                               width_field="width_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    es_libre = models.BooleanField(default=True)
    costo = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    numero_visitas = models.PositiveIntegerField(default=0)
    organizador = models.ForeignKey(
        settings.AUTH_USER_MODEL)  # Falta crear  Usuarios

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.nombre)
        super(Evento, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Evento"
        verbose_name_plural = "Eventos"

    def __str__(self):
        return self.nombre

eventus/apps/events/models/registro.py
from django.db import models
from .categoria import TimeStampModel
from ..choices.enums import GENERO_CHOICES, PROVINCIAS_CHOICES, ENTERECE_CHOICES


class Registro(TimeStampModel):
    nombre = models.CharField(max_length=80)
    apellidos = models.CharField(max_length=150)
    email = models.EmailField()
    celular = models.CharField(max_length=9)
    organizacion = models.CharField(max_length=150)
    provincia = models.CharField(max_length=100, choices=PROVINCIAS_CHOICES)
    distrito = models.CharField(max_length=100)
    genero = models.CharField(
        max_length=40, choices=GENERO_CHOICES, blank=True)
    edad = models.IntegerField()
    me_entere = models.CharField(
        max_length=60, choices=ENTERECE_CHOICES, blank=True)

    class Meta:
        verbose_name = "Registro"
        verbose_name_plural = "Registros"

    def __str__(self):
        return self.nombre

eventus/apps/events/forms.py
from django import forms
from .models.evento import Evento
from .models.registro import Registro


class EventoForm(forms.ModelForm):

    class Meta:
        model = Evento
        exclude = ('views', 'created', 'modified',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'summary': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'place': forms.TextInput(attrs={'class': 'form-control'}),
            'start': forms.DateTimeInput(attrs={'class': 'form-control'}),
            'finish': forms.DateTimeInput(attrs={'class': 'form-control'}),
            'imagen': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'is_free': forms.CheckboxInput(),
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
        }


class RegistroForm(forms.ModelForm):

    class Meta:
        model = Registro
        fields = (
            'nombre',
            'apellidos',
            'email',
            'celular',
            'organizacion',
            'provincia',
            'distrito',
            'genero',
            'edad',
            'me_entere',
        )

eventus/apps/events/views.py
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView
from .models.evento import Evento
from .models.categoria import Categoria
from .models.registro import Registro
from .forms import EventoForm, RegistroForm

# Create your views here.


from django.core.urlresolvers import reverse_lazy


# seccion de creacion views de  registro

class MainRegistroPanelView(TemplateView):

    template_name = 'events/registro/registro.html'

    def get_context_data(self, **kwargs):
        context = super(MainRegistroPanelView, self).get_context_data(**kwargs)
        context['asistentes'] = Registro.objects.all()
        return context


class CrearRegistro(CreateView):

    form_class = RegistroForm
    template_name = 'events/registro/crear_registro.html'
    success_url = reverse_lazy('events_app:registropanel')

    def form_valid(self, form):

        return super(CrearRegistro, self).form_valid(form)


# Seccion de creacion de views de Evento

class IndexView(TemplateView):

    template_name = 'events/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['events'] = Evento.objects.all()
        context['categorias'] = Categoria.objects.all()
        return context


class MainPanelView(TemplateView):

    template_name = 'events/panel/panel.html'

    def get_context_data(self, **kwargs):
        context = super(MainPanelView, self).get_context_data(**kwargs)
        context['events'] = Evento.objects.all()
        context['cantidad'] = context['events'].count()
        return context


class EventDetail(DetailView):

    template_name = 'events/panel/detalle_evento.html'
    model = Evento


class CreateEvent(CreateView):

    form_class = EventoForm
    template_name = 'events/panel/crear_evento.html'
    success_url = reverse_lazy('events_app:panel')

    def form_valid(self, form):
        form.instance.organizer = self.request.user
        return super(CreateEvent, self).form_valid(form)


class EventEdit(UpdateView):

    template_name = 'events/panel/editar_evento.html'
    success_url = reverse_lazy('events_app:panel')
    model = Evento
    form_class = EventoForm

    def form_valid(self, form):
        form.instance.organizer = self.request.user
        return super(EventEdit, self).form_valid(form)


class EventDelete(DeleteView):

    template_name = 'events/panel/eliminar_evento.html'
    model = Evento
    success_url = reverse_lazy('events_app:panel')
    context_object_name = 'event'

eventus/apps/events/templates/events/panel/base_panel.html
{% extends "events/base_events.html" %}

{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
{% endblock css %}

{% block js %}
    <script src="{% static 'js/bootstrap.js' %}"></script>
{% endblock js %}

eventus/apps/events/templates/events/panel/crear_evento.html
{% extends "events/base_events.html" %}

{% block title %}Panel{% endblock title %}

{% block content %}

    {% include "events/panel/navbar.html" %}

    <div class="container">

        <div class="page-header">
            <h4>
                <a href="{% url 'events_app:panel' %}" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>
                <strong>Crear evento</strong>
            </h4>
        </div><!-- page-header -->

        <div class="row">
            
            <div class="col-md-12">

                <form role="form" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <p class="lead"><span class="glyphicon glyphicon-info-sign"></span> Ingresa los datos de tu evento y compartelo con todos tus conocidos o amigos.</p>

                    {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ form.errors }}
                        </div>
                    {% endif %}

                    <div class="form-group">
                        <label>{{ form.nombre.label_tag }}</label>
                        {{ form.nombre }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.resumen.label_tag }}</label>
                        {{ form.resumen }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.contenido.label_tag }}</label>
                        {{ form.contenido}}
                    </div>

                    <div class="form-group">
                        <label>{{ form.categoria.label_tag }}</label>
                        {{ form.categoria }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.lugar.label_tag }}</label>
                        {{ form.lugar }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.fecha_inicio.label_tag }}</label>
                        {{ form.fecha_inicio }}
                        <p class="help-block">Ingresa cuando inciará el evento. DD/MM/AA HH:MM:SS.</p>
                    </div>

                    <div class="form-group">
                        <label>{{ form.fecha_fin.label_tag }}</label>
                        {{ form.fecha_fin }}
                        <p class="help-block">Ingresa cuando finalizará el evento. DD/MM/AA HH:MM:SS.</p>
                    </div>

                    <div class="form-group">
                        <label>{{ form.imagen.label_tag }}</label>
                        {{ form.imagen }}
                    </div>

                    <div class="checkbox">
                        <label>
                            {{ form.es_libre }} {{ form.es_libre.label_tag }}
                        </label>
                    </div>
                    
                    <div class="form-group">
                        <label>{{ form.costo.label }}</label>
                        {{ form.costo }}
                    </div>
                    
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Guardar evento</button>
                    </div>
                </form>

            </div><!-- col-md-12 -->

        </div><!-- /row -->

    </div><!-- /container -->

{% endblock content %}

eventus/apps/events/templates/events/panel/detalle_evento.html
{% extends "events/base_events.html" %}

{% block title %}Panel{% endblock title %}

{% block content %}

    {% include "events/panel/navbar.html" %}

    <div class="container">

        <div class="page-header">
            <h4>
                <a href="{% url 'events_app:panel' %}" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>
                <strong>Evento: {{ event.name }}</strong>
            </h4>
        </div><!-- page-header -->

        <div class="row">
            
            <div class="col-md-3 text-center">
                <img src="{{ event.imagen.url }}" alt="{{ event.name }}" class="img-rounded">
            </div>

            <div class="col-md-9">

                <table class="table">
                    <tbody>
                        <tr>
                            <th>Name</th>
                            <td>{{ event.name }}</td>
                        </tr>
                        <tr>
                            <th>Category</th>
                            <td>{{ event.category }}</td>
                        </tr>
                        <tr>
                            <th>Content</th>
                            <td>{{ event.content }}</td>
                        </tr>
                        <tr>
                            <th>Start / Finish</th>
                            <td>{{ event.start }} / {{ event.finish }}</td>
                        </tr>
                        <tr>
                            <th>Place</th>
                            <td>{{ event.place }}</td>
                        </tr>
                        <tr>
                            <th>Amount</th>
                            {% if event.is_free %}
                                <td><span class="label label-default">Gratuito</span></td>
                            {% else %}
                                <td><span class="label label-info">S/. {{ event.amount }}</span></td>
                            {% endif %}
                        </tr>
                    </tbody>
                </table>

            </div><!-- col-md-12 -->

        </div><!-- /row -->

    </div><!-- /container -->

{% endblock content %}

eventus/apps/events/templates/events/panel/editar_evento.html
{% extends "events/base_events.html" %}

{% block title %}Panel{% endblock title %}

{% block content %}

    {% include "events/panel/navbar.html" %}

    <div class="container">

        <div class="page-header">
            <h4>
                <a href="{% url 'events_app:panel' %}" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>
                <strong>Editando: {{ event.name }}</strong>
            </h4>
        </div><!-- page-header -->

        <div class="row">
            
            <div class="col-md-12">

                <form role="form" action="{% url 'events_app:editar' event.id %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <p class="lead"><span class="glyphicon glyphicon-info-sign"></span> Ingresa los datos del evento para cambiar los datos.</p>

                    {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ form.errors }}
                        </div>
                    {% endif %}

                    <div class="form-group">
                        <label>{{ form.name.label_tag }}</label>
                        {{ form.name }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.summary.label_tag }}</label>
                        {{ form.summary }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.content.label_tag }}</label>
                        {{ form.content }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.category.label_tag }}</label>
                        {{ form.category }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.place.label_tag }}</label>
                        {{ form.place }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.start.label_tag }}</label>
                        {{ form.start }}
                        <p class="help-block">Ingresa cuando inciará el evento. DD/MM/AA HH:MM:SS.</p>
                    </div>

                    <div class="form-group">
                        <label>{{ form.finish.label_tag }}</label>
                        {{ form.finish }}
                        <p class="help-block">Ingresa cuando finalizará el evento. DD/MM/AA HH:MM:SS.</p>
                    </div>

                    <div class="form-group">
                        <label>{{ form.imagen.label_tag }}</label>
                        {{ form.imagen }}
                    </div>

                    <div class="checkbox">
                        <label>
                            {{ form.is_free }} {{ form.is_free.label_tag }}
                        </label>
                    </div>
                    
                    <div class="form-group">
                        <label>{{ form.amount.label }}</label>
                        {{ form.amount }}
                    </div>
                    
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Guardar evento</button>
                    </div>
                </form>

            </div><!-- col-md-12 -->

        </div><!-- /row -->

    </div><!-- /container -->

{% endblock content %}

eventus/apps/events/templates/events/panel/eliminar_evento.html
{% extends "events/base_events.html" %}

{% block title %}Panel{% endblock title %}

{% block content %}

    {% include "events/panel/navbar.html" %}

    <div class="container">

        <div class="page-header">
            <h4>
                <strong>Editando: {{ event.name }}</strong>
            </h4>
        </div><!-- page-header -->

        <div class="row">
            
            <div class="col-md-12">

                <form role="form" action="{% url 'events_app:eliminar' event.id %}" method="POST">{% csrf_token %}
                    <p class="">¿Desea eliminar el evento "{{ event.name }}"?</p>

                    <input type="submit" value="Sí" class="btn btn-danger"> 
                    <a href="{% url 'events_app:panel' %}" class="btn btn-default">No</a>
                </form>

            </div><!-- col-md-12 -->

        </div><!-- /row -->

    </div><!-- /container -->

{% endblock content %}

eventus/apps/events/templates/events/panel/navbar.html
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'events_app:index' %}">Eventus</a>
        </div>
    </div>
</div>

eventus/apps/events/templates/events/panel/panel.html
{% extends "events/base_events.html" %}

{% block title %}Panel{% endblock title %}

{% block content %}

    {% include "events/panel/navbar.html" %}

    <div class="container">

        <div class="page-header">
            <h4>
                <strong>Tienes <span class="label label-warning">{{ cantidad }}</span> Eventos disponibles </strong>
                <a class="btn btn-primary pull-right" href="{% url 'events_app:nuevo' %}">
                    <span class="glyphicon glyphicon-plus"></span> Crear un evento nuevo
                </a>
            </h4>
        </div><!-- page-header -->

        <div class="row">
            
            <div class="col-md-12">
                
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th colspan="2">Nombre del evento</th>
                            <th>Categoría</th>
                            <th>Inicio</th>
                            <th>Fin</th>
                            <th>Monto</th>
                            <th class="text-center">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for event in events %}
                        <tr>
                            <td>
                            <td>{{ event.nombre }}</td>
                            <td>{{ event.categoria }}</td>
                            <td>{{ event.fecha_inicio }}</td>
                            <td>{{ event.fecha_fin }}</td>
                            <td>{{ event.costo }}</td>

                            </td>
                            <td class="text-right">
                                <a href="{% url 'events_app:detalle' event.id %}" class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>
                                <a href="" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                                <a href="" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div><!-- col-md-12 -->

        </div><!-- /row -->

    </div><!-- /container -->

{% endblock content %}